#!/usr/bin/env python3
# PYTHON_ARGCOMPLETE_OK

"""Build doc-gen4 docs locally and publish to gh-pages.

Design goals (per repo request):
- Manual website sources live on main branch under `site/`.
- Autogenerated Lean docs are produced by doc-gen4.
- The result (manual + autogenerated) is written into the `gh-pages` branch.
- If docs build fails, keep previous gh-pages output as a fallback (stale),
  but inject a prominent disclaimer into the generated HTML.
- If docs build succeeds, recreate gh-pages content from scratch.

Usage:
  python3 scripts/build-gh-pages.py
  python3 scripts/build-gh-pages.py --push

Notes:
- This script uses `git worktree` to avoid clobbering your current checkout.
- It expects to run from anywhere inside the git repo.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


STALE_BANNER_START = "<!-- STALE_BUILD_BANNER_START -->"
STALE_BANNER_END = "<!-- STALE_BUILD_BANNER_END -->"

# Set by --verbose.
VERBOSE = False

# Where to redirect missing dependency module pages.
# mathlib4_docs hosts docs for Mathlib + core libs (Init/Std/Lean/Lake) + common packages.
MATHLIB_DOCS_BASE = "https://leanprover-community.github.io/mathlib4_docs/"


def run(
    cmd: list[str],
    *,
    cwd: Path | None = None,
    check: bool = True,
    verbose: bool = False,
    env: dict[str, str] | None = None,
) -> subprocess.CompletedProcess:
    """Run a subprocess command and capture combined stdout/stderr.

    If `--verbose` is enabled (global `VERBOSE`) or `verbose=True` is passed, the
    executed command is printed (with cwd).

    This helper is used for all git/lake invocations so that:
    - output can be included in build logs
    - failures can be handled explicitly (`check=False`)
    """
    if verbose or VERBOSE:
        where = f" (cwd={cwd})" if cwd else ""
        print("$ " + " ".join(cmd) + where)
    return subprocess.run(
        cmd,
        cwd=str(cwd) if cwd else None,
        check=check,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        env={**os.environ, **env} if env else None,
    )


def repo_root() -> Path:
    """Return the git repository root directory."""
    p = run(["git", "rev-parse", "--show-toplevel"]).stdout.strip()
    return Path(p)


def detect_project_root_module(root: Path) -> str:
    """Pick the main project lean_lib name from lakefile.toml.

    Heuristic: return the first `[[lean_lib]] name = "..."` that is not DocEntrypoint.
    """
    # We keep this simple: the lakefile already declares the project lean libs.
    # If the repo adds more lean_libs later, we still pick the first non-doc-entrypoint.
    text = read_text(root / "lakefile.toml")
    m = re.findall(r"\[\[lean_lib\]\]\s*\n\s*name\s*=\s*\"([^\"]+)\"", text)
    for name in m:
        if name != "DocEntrypoint":
            return name
    return "GaudisCrypt"


def module_name_from_html_path(project_root: str, rel: Path) -> str | None:
    """Convert `GaudisCrypt/Foo/Bar.html` -> `GaudisCrypt.Foo.Bar`."""
    # Used to map doc-gen4 HTML file paths back to Lean module names.
    if rel.suffix != ".html":
        return None
    parts = list(rel.with_suffix("").parts)
    if not parts:
        return None
    if parts[0] != project_root:
        return None
    return ".".join(parts)


def module_to_rel_html(project_root: str, mod: str) -> Path:
    """Map a module name to a doc-gen4 relative HTML path.

    Examples:
    - `GaudisCrypt` -> `GaudisCrypt.html`
    - `GaudisCrypt.Language.Modules` -> `GaudisCrypt/Language/Modules.html`
    """
    parts = mod.split(".")
    if mod == project_root:
        return Path(f"{project_root}.html")
    return Path(*parts).with_suffix(".html")


def generate_project_navbar(doc_dir: Path, project_root: str, modules: list[str]) -> str:
    """Generate a navbar.html that links only to project theories.

    This intentionally omits the "General documentation" section.
    The view is hierarchical: `GaudisCrypt` contains `Lib`, `Logic`, etc.
    """

    # Note: We generate a navbar.html that is "close enough" to doc-gen4's navbar
    # so that the existing CSS (style.css) continues to work.
    #
    # Important detail: for excluded modules we might not have a local html file.
    # In that case we render them as non-clickable leaves.

    # Build a module tree from module name components.
    class Node:
        """A node in the module hierarchy tree."""
        __slots__ = ("name", "children", "mod")

        def __init__(self, name: str):
            self.name = name
            self.children: dict[str, Node] = {}
            self.mod: str | None = None

    root_node = Node(project_root)

    # Ensure stable order and uniqueness.
    seen: set[str] = set()
    ordered = []
    for m in modules:
        if not m.startswith(project_root):
            continue
        if m in seen:
            continue
        seen.add(m)
        ordered.append(m)
    ordered.sort()

    # Insert each module into the tree.
    for mod in ordered:
        parts = mod.split(".")
        if not parts or parts[0] != project_root:
            continue
        cur = root_node
        for p in parts[1:]:
            cur = cur.children.setdefault(p, Node(p))
        cur.mod = mod

    def link_for(mod: str) -> str | None:
        """Return a local href for `mod` if the corresponding HTML exists."""
        rel = module_to_rel_html(project_root, mod)
        if (doc_dir / rel).exists():
            return "./" + rel.as_posix()
        return None

    def render_node(node: Node, prefix_path: str) -> str:
        """Render the children of `node` (root-level expansion helper)."""
        # prefix_path is like "./GaudisCrypt/Lib.html" for data-path hints.
        # This matches doc-gen4's general structure enough to keep CSS working.
        parts: list[str] = []
        # Root: render its children, no outer <details> wrapper.
        for key in sorted(node.children.keys()):
            child = node.children[key]
            # Determine module name for this node if it corresponds to a module.
            # E.g. GaudisCrypt.Lib corresponds to module GaudisCrypt.Lib (rare), but typically
            # only leaves exist. We still allow a file link if an html exists.
            # Compute full module name by walking from root in recursion.
            # We'll pass it down as prefix_path only for data-path; actual file link is computed.

            rendered = render_subtree(child, parent_mod=(project_root + ("." + child.name if child.name else "")))
            parts.append(rendered)
        return "".join(parts)

    def render_subtree(node: Node, parent_mod: str) -> str:
        """Render a subtree as nested <details> sections and leaf links."""
        # parent_mod is the module name at this node (even if there is no file).
        file_link = link_for(parent_mod)

        if node.children:
            # Directory node.
            # Summary shows short name, optionally with a file link.
            if file_link:
                summary = f'{escape_html(node.name)} (<a href="{file_link}">file</a>)'
            else:
                summary = escape_html(node.name)
            inner = []
            # If this node is also a module leaf and has a file, add it as a link entry.
            if node.mod and file_link:
                inner.append(f'<div class="nav_link"><a class="break_within" href="{file_link}">{escape_html(node.name)}</a></div>')
            for key in sorted(node.children.keys()):
                child = node.children[key]
                inner.append(render_subtree(child, parent_mod=parent_mod + "." + child.name))
            return f'<details class="nav_sect" data-path="{file_link or ""}"><summary>{summary}</summary>{"".join(inner)}</details>'

        # Leaf node.
        href = link_for(node.mod or parent_mod)
        label = escape_html(node.name)
        if href:
            return f'<div class="nav_link"><a class="break_within" href="{href}">{label}</a></div>'
        else:
            return f'<div class="nav_link"><span class="break_within">{label}</span></div>'

    # Render root as a single open <details> so it's nicely grouped.
    root_link = link_for(project_root)
    root_summary = escape_html(project_root)
    if root_link:
        root_summary = f'{escape_html(project_root)} (<a href="{root_link}">file</a>)'

    body = (
        '<div class="navframe"><nav class="nav">'
        '<div class="module_list">'
        f'<details class="nav_sect" open="true" data-path="{root_link or ""}"><summary>{root_summary}</summary>'
        + render_node(root_node, "")
        + '</details>'
        '</div></nav></div>'
    )

    return (
        '<html lang="en"><head>'
        '<meta charset="UTF-8"></meta>'
        '<meta name="viewport" content="width=device-width, initial-scale=1"></meta>'
        '<link rel="stylesheet" href="./style.css"></link>'
        '<link rel="icon" href="./favicon.svg"></link>'
        '<link rel="mask-icon" href="./favicon.svg" color="#000000"></link>'
        '<link rel="prefetch" href=".//declarations/declaration-data.bmp" as="image"></link>'
        '<script type="module" src="./nav.js"></script>'
        '<script type="module" src="./color-scheme.js"></script>'
        '<base target="_parent"></base>'
        '</head><body>'
        + body
        + '</body></html>'
    )


def prune_nonproject_modules(doc_dir: Path, project_root: str) -> None:
    """Delete generated module pages/dirs not belonging to our project."""
    # After doc-gen4 generates docs, the `doc/` directory contains many dependency
    # pages (Mathlib, Std, Lean, etc.). We remove them so that the published docs
    # only contain our project.
    keep_root_files = {
        "index.html",
        "404.html",
        "navbar.html",
        "search.html",
        "foundational_types.html",
        "tactics.html",
        "references.html",
        "references.bib",
    }
    keep_dirs = {
        project_root,
        "find",
        "declarations",
        # some doc-gen4 versions may have this
        "src",
    }

    for child in doc_dir.iterdir():
        if child.is_dir() and not child.is_symlink():
            if child.name in keep_dirs:
                continue
            shutil.rmtree(child)
            continue
        if child.is_file() and child.suffix.lower() == ".html":
            if child.name in keep_root_files:
                continue
            child.unlink(missing_ok=True)


def rewrite_broken_links_to_online_docs(docs_root: Path) -> None:
    """Rewrite links to missing local .html pages to mathlib4_docs.

    This is intended to run after pruning non-project docs. At that point links to
    dependency modules (Mathlib/Std/Lean/...) would be broken locally; we rewrite
    them to the public documentation site.
    """

    # Strategy:
    # - Scan every HTML file we publish.
    # - For each href="..." attribute, if it points to a local .html page that no
    #   longer exists (because we pruned it), rewrite it to mathlib4_docs.
    # - Preserve any fragment (#...) and query string (?...) suffix.

    # Regex is intentionally simple: doc-gen4 emits plain href="..." attributes.
    href_re = re.compile(r"href=\"([^\"]+)\"")

    scanned_files = 0
    seen_links = 0
    rewritten = 0
    rewritten_targets: dict[str, int] = {}

    for html_path in iter_html_files(docs_root):
        scanned_files += 1
        html = read_text(html_path)
        changed = False

        def replace(m: re.Match[str]) -> str:
            nonlocal seen_links, rewritten, changed
            href = m.group(1)
            seen_links += 1

            # Skip external links and fragment-only links.
            if href.startswith("http://") or href.startswith("https://"):
                return m.group(0)
            if href.startswith("#"):
                return m.group(0)
            if href.startswith("mailto:") or href.startswith("javascript:"):
                return m.group(0)

            # Split off query/fragment.
            path_part = href
            suffix = ""
            for sep in ["#", "?"]:
                if sep in path_part:
                    base, rest = path_part.split(sep, 1)
                    path_part = base
                    suffix = sep + rest + suffix

            if not path_part.endswith(".html"):
                return m.group(0)

            # Resolve the target relative to the current HTML file.
            # Example: in `GaudisCrypt/Language/Modules.html`, a link like
            # `../.././Mathlib/.../AList.html` becomes a filesystem path under docs_root.
            base_dir = html_path.parent
            target_fs = (base_dir / path_part).resolve()

            try:
                rel_to_docs = target_fs.relative_to(docs_root.resolve())
            except Exception:
                # Target points outside docs_root; don't rewrite.
                return m.group(0)

            # If it exists locally, keep.
            if target_fs.exists():
                return m.group(0)

            # Rewrite missing local target to mathlib4_docs.
            new_href = MATHLIB_DOCS_BASE + rel_to_docs.as_posix() + suffix
            rewritten += 1
            changed = True
            rewritten_targets[str(rel_to_docs)] = rewritten_targets.get(str(rel_to_docs), 0) + 1
            return f'href="{new_href}"'

        new_html = href_re.sub(replace, html)
        if changed and new_html != html:
            write_text(html_path, new_html)

    if VERBOSE:
        print(f"link rewrite: scanned {scanned_files} html files")
        print(f"link rewrite: saw {seen_links} href attributes")
        print(f"link rewrite: rewrote {rewritten} links to {MATHLIB_DOCS_BASE}")
        if rewritten_targets:
            top = sorted(rewritten_targets.items(), key=lambda kv: kv[1], reverse=True)[:10]
            print("link rewrite: top rewritten targets:")
            for k, v in top:
                print(f"  {k}  ({v})")


# doc-gen4 emits its own favicon <link> tags (referencing favicon.svg). Any
# <link> whose rel contains "icon" (icon, mask-icon, apple-touch-icon, ...) is a
# favicon declaration we want to replace. Group 1 captures the leading indent so
# we can preserve formatting when substituting our own tags.
FAVICON_LINK_RE = re.compile(
    r"([ \t]*)<link\b[^>]*\brel=\"[^\"]*icon[^\"]*\"[^>]*>[ \t]*\n?",
    re.IGNORECASE,
)


def retarget_doc_favicon(docs_root: Path) -> None:
    """Point the generated API docs at the main site favicon.

    doc-gen4 references its own `favicon.svg`, which shows a favicon in the
    `lean/` subfolder different from the rest of the site. We replace those tags
    with links to the main site favicon (`favicon.ico`/`favicon.png`, published at
    the gh-pages root), so the API docs match the rest of the site.
    """
    # The manual site favicon lives at the gh-pages root, one level above `lean/`.
    site_root = docs_root.parent
    scanned = 0
    changed_files = 0
    for html_path in iter_html_files(docs_root):
        scanned += 1
        html = read_text(html_path)
        if not FAVICON_LINK_RE.search(html):
            continue

        # Relative path from this page's directory up to the gh-pages root.
        rel = os.path.relpath(site_root, start=html_path.parent).replace(os.sep, "/")
        prefix = "" if rel == "." else rel + "/"

        # Replace the first favicon <link> with our pair; drop any others.
        state = {"first": True}

        def replace(m: re.Match[str]) -> str:
            indent = m.group(1)
            if state["first"]:
                state["first"] = False
                return (
                    f'{indent}<link rel="icon" href="{prefix}favicon.ico" sizes="any">\n'
                    f'{indent}<link rel="icon" href="{prefix}favicon.png" type="image/png" sizes="256x256">\n'
                )
            return ""

        new_html = FAVICON_LINK_RE.sub(replace, html)
        if new_html != html:
            write_text(html_path, new_html)
            changed_files += 1
    if VERBOSE:
        print(f"favicon retarget: scanned {scanned} html files, updated {changed_files}")


def postprocess_doc_tree(doc_dir: Path, project_root: str) -> None:
    """Restrict docs nav + delete non-project module pages."""
    # This is called right after copying doc-gen4 output into the publish directory.
    # It removes dependency pages, but does NOT yet write navbar.html (we do that
    # after restoring excluded theories, so the navbar can include them).
    prune_nonproject_modules(doc_dir, project_root)
    # Point the API docs at the main site favicon so they don't differ from it.
    retarget_doc_favicon(doc_dir)
    # Navbar is generated later, after excluded theories are restored.


def build_navbar_module_list(project_root: str, *, generated_relpaths: set[Path], excluded: set[str]) -> list[str]:
    """Compute the set of project modules that should appear in the navbar.

    - All generated project modules (from manifest)
    - Plus all excluded modules (even if their HTML came from stale gh-pages)
    """
    # Note: generated_relpaths contains *all* doc-gen4 outputs. We only include
    # those under the project root.
    mods: set[str] = set()
    for rel in generated_relpaths:
        m = module_name_from_html_path(project_root, rel)
        if m:
            mods.add(m)
    mods |= set(excluded)
    return sorted(mods)


def current_head_sha(root: Path) -> str:
    """Return the current git HEAD SHA."""
    return run(["git", "rev-parse", "HEAD"], cwd=root).stdout.strip()


def git_branch_exists(root: Path, branch: str) -> bool:
    """Return True if the given local git branch exists."""
    cp = run(["git", "show-ref", "--verify", f"refs/heads/{branch}"], cwd=root, check=False)
    return cp.returncode == 0


def git_remote_branch_exists(root: Path, remote: str, branch: str) -> bool:
    """Return True if `remote` has `branch`, even if it isn't fetched locally."""
    cp = run(["git", "ls-remote", "--heads", remote, branch], cwd=root, check=False)
    return cp.returncode == 0 and bool(cp.stdout.strip())


def ensure_worktree(root: Path, branch: str, worktree_dir: Path) -> None:
    """Ensure `worktree_dir` is a git worktree checked out at `branch`.

    The script uses worktrees so we can update `gh-pages` without touching the
    current working directory.
    """
    # Clean up any stale registration first (e.g. previous crash).
    run(["git", "worktree", "prune"], cwd=root, check=False)
    if worktree_dir.exists():
        # If it already exists, it might be a stale checkout. Remove and recreate.
        run(["git", "worktree", "remove", "--force", str(worktree_dir)], cwd=root, check=False)
        shutil.rmtree(worktree_dir, ignore_errors=True)
    worktree_dir.parent.mkdir(parents=True, exist_ok=True)

    # If the branch already has an attached worktree, `git worktree add` fails.
    # We proactively remove it to make the script idempotent.
    cp = run(["git", "worktree", "list", "--porcelain"], cwd=root, check=False)
    if cp.returncode == 0:
        lines = cp.stdout.splitlines()
        cur_path = None
        cur_branch = None
        for line in lines + [""]:
            if line.startswith("worktree "):
                cur_path = line[len("worktree ") :].strip()
                cur_branch = None
            elif line.startswith("branch "):
                cur_branch = line[len("branch ") :].strip()
            elif line == "":
                if cur_path and cur_branch == f"refs/heads/{branch}":
                    # Don't remove the main checkout.
                    if Path(cur_path).resolve() != root.resolve():
                        run(["git", "worktree", "remove", "--force", cur_path], cwd=root, check=False)
                cur_path = None
                cur_branch = None

    if git_branch_exists(root, branch):
        run(["git", "worktree", "add", str(worktree_dir), branch], cwd=root)
        return

    # If the remote branch exists but the user didn't fetch it, creating a new
    # local branch off HEAD would later make `git push origin <branch>` fail
    # (non-fast-forward). Detect via ls-remote and fetch only that branch.
    remote = "origin"
    if git_remote_branch_exists(root, remote, branch):
        # Create the remote-tracking ref without fetching other branches.
        run(["git", "fetch", remote, f"{branch}:refs/remotes/{remote}/{branch}"], cwd=root)
        run(["git", "worktree", "add", "-b", branch, str(worktree_dir), f"{remote}/{branch}"], cwd=root)
        return

    # Remote doesn't have the branch (or no remote configured): create it.
    # The script will wipe the worktree before writing gh-pages content.
    run(["git", "worktree", "add", "-b", branch, str(worktree_dir), "HEAD"], cwd=root)



def remove_all_except_git(worktree_root: Path, *, preserve: set[str] | None = None) -> None:
    """Delete everything in the worktree except `.git` and preserved names."""
    preserve = preserve or set()
    for child in worktree_root.iterdir():
        if child.name == ".git":
            continue
        if child.name in preserve:
            continue
        if child.is_dir() and not child.is_symlink():
            shutil.rmtree(child)
        else:
            child.unlink(missing_ok=True)


def copy_tree(src: Path, dst: Path) -> None:
    """Recursively copy `src` into `dst` (like `cp -R`)."""
    if not src.exists():
        return
    dst.mkdir(parents=True, exist_ok=True)
    for root, dirs, files in os.walk(src):
        r = Path(root)
        rel = r.relative_to(src)
        (dst / rel).mkdir(parents=True, exist_ok=True)
        for d in dirs:
            (dst / rel / d).mkdir(parents=True, exist_ok=True)
        for f in files:
            s = r / f
            t = dst / rel / f
            shutil.copy2(s, t)


def run_jekyll_build(site_src: Path, site_dst: Path) -> None:
    """Build the Jekyll site locally into `site_dst`.

    Uses Bundler if `Gemfile` exists; otherwise tries `jekyll` directly.
    """
    try:
        if (site_src / "Gemfile").exists():
            if shutil.which("bundle") is None:
                raise SystemExit(
                    "Missing `bundle` (Ruby Bundler), required because docs/website contains a Gemfile.\n"
                    "Install Ruby + Bundler, then retry. For example:\n"
                    "  gem install bundler\n"
                    "Or via your OS package manager (e.g. `apt install ruby-full` / `brew install ruby`)."
                )

            # Ensure Gemfile.lock is consistent; keep it local to the repo.
            run(["bundle", "install"], cwd=site_src)
            run(
                ["bundle", "exec", "jekyll", "build", "--source", str(site_src), "--destination", str(site_dst)],
                cwd=site_src,
            )
        else:
            if shutil.which("jekyll") is None:
                raise SystemExit(
                    "Missing `jekyll` (Ruby). Install Ruby + Jekyll, then retry. For example:\n"
                    "  gem install jekyll\n"
                    "Or use Bundler by adding a Gemfile under docs/website/."
                )
            run(["jekyll", "build", "--source", str(site_src), "--destination", str(site_dst)], cwd=site_src)
    except subprocess.CalledProcessError as e:
        # Avoid a Python traceback; surface the failing command and its output.
        out = getattr(e, "stdout", None) or getattr(e, "output", None) or ""
        raise SystemExit(
            "Jekyll build failed. Ensure Ruby dependencies are installed and the site builds locally.\n"
            f"Command: {' '.join(map(str, e.cmd))}\n\n"
            f"Output:\n{out}"
        )


def read_text(path: Path) -> str:
    """Read a file as UTF-8, replacing errors."""
    return path.read_text(encoding="utf-8", errors="replace")


def write_text(path: Path, content: str) -> None:
    """Write a UTF-8 file, creating parent directories."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def strip_stale_banner(html: str) -> str:
    """Remove our injected banner block (if present)."""
    if STALE_BANNER_START not in html:
        return html
    # Remove any existing banner block.
    pattern = re.compile(re.escape(STALE_BANNER_START) + r".*?" + re.escape(STALE_BANNER_END) + r"\s*", re.DOTALL)
    return re.sub(pattern, "", html)


def inject_stale_banner(html: str, banner_html: str) -> str:
    """Insert a banner into the HTML.

    Prefer inserting into `<main>` (first child) because doc-gen pages use `<main>`
    for the page content; falling back to `<body>` keeps it robust.
    """
    html = strip_stale_banner(html)

    # Prefer inserting into <main> as the first child.
    m = re.search(r"<main[^>]*>", html, flags=re.IGNORECASE)
    if m:
        insert_at = m.end()
        return html[:insert_at] + "\n" + banner_html + html[insert_at:]

    # Fallback: insert right after the opening <body ...> tag.
    if "<body" not in html:
        return banner_html + "\n" + html
    m = re.search(r"<body[^>]*>", html, flags=re.IGNORECASE)
    if not m:
        return banner_html + "\n" + html
    insert_at = m.end()
    return html[:insert_at] + "\n" + banner_html + html[insert_at:]


def banner_block(*, head_sha: str, build_time_utc: str, error_excerpt: str) -> str:
    """Build a detailed (build-level) banner. (Not currently used for site index.)"""
    safe_excerpt = (error_excerpt or "").strip()
    if len(safe_excerpt) > 2000:
        safe_excerpt = safe_excerpt[:2000] + "\n… (truncated)"
    pre = ""
    if safe_excerpt:
        pre = f"<pre style=\"margin: .75rem 0 0; white-space: pre-wrap;\">{escape_html(safe_excerpt)}</pre>"
    return (
        f"{STALE_BANNER_START}\n"
        "<div style=\"background:#7f1d1d;color:#fff;padding:12px 14px;line-height:1.35;\">"
        "<strong>Warning:</strong> This documentation build is stale/partial because the latest doc build failed. "
        "Some pages may not correspond to the current main branch."
        f"<div style=\"opacity:.9;margin-top:6px\">Commit: <code>{head_sha}</code> (attempted) | "
        f"Time (UTC): <code>{build_time_utc}</code></div>"
        f"{pre}"
        "</div>\n"
        f"{STALE_BANNER_END}\n"
    )


def stale_theory_banner_block(*, head_sha: str, build_time_utc: str) -> str:
    """Build the per-theory stale banner injected into old HTML pages."""
    _ = head_sha, build_time_utc
    return (
        f"{STALE_BANNER_START}\n"
        "<div style=\"background:#7f1d1d;color:#fff;padding:12px 14px;line-height:1.35;\">"
        "<strong>Warning:</strong> This theory currently does not build correctly. "
        "Therefore the documentation refers to an older version of the file."
        "</div>\n"
        f"{STALE_BANNER_END}\n"
    )


def module_to_html_relpath(mod: str) -> Path:
    """Convert a module name to its HTML path relative to docs root."""
    parts = mod.split(".")
    return Path(*parts).with_suffix(".html")


def is_generated_this_run(doc_dir: Path | None, rel: Path) -> bool:
    """Deprecated: we now use doc-manifest.json to detect generated pages."""
    # We consider a module HTML "generated" iff it appears in doc-gen4's manifest.
    # This avoids false positives when stale fallback pages share the same path.
    return False


def load_doc_manifest(doc_dir: Path) -> set[Path]:
    """Read `.lake/build/doc-manifest.json` and return relative doc paths."""
    # doc-gen4 writes a JSON array of strings like "doc/Foo/Bar.html".
    manifest_path = doc_dir.parent / "doc-manifest.json"
    if not manifest_path.exists():
        return set()
    try:
        data = json.loads(read_text(manifest_path))
        out: set[Path] = set()
        for s in data:
            # entries are like "doc/Foo/Bar.html"
            if isinstance(s, str) and s.startswith("doc/"):
                out.add(Path(s[len("doc/") :]))
        return out
    except Exception:
        return set()


def iter_html_files(root_dir: Path) -> list[Path]:
    """Return all .html files under `root_dir` (recursive)."""
    out: list[Path] = []
    if not root_dir.exists():
        return out
    for dp, _, files in os.walk(root_dir):
        for f in files:
            if f.endswith(".html"):
                out.append(Path(dp) / f)
    return out


def reset_docgen_outputs(root: Path) -> None:
    """Remove doc-gen4 build outputs so transitive closure can't go stale.

    doc-gen4 stores its DB and marker files under `.lake/build`. If we change the
    generated entrypoint imports between attempts, those stale DB rows would
    otherwise keep old modules in the transitive closure and we'd regenerate HTML
    for modules that are no longer imported.
    """
    # We do this before each build attempt because doc-gen4's DB is incremental.
    # If we remove imports from the autogenerated entrypoint, we don't want old
    # modules to keep showing up as transitive dependencies.
    build = root / ".lake" / "build"
    # If the project hasn't been built yet, nothing to do.
    if not build.exists():
        return
    # Database used by doc-gen4
    (build / "api-docs.db").unlink(missing_ok=True)
    # Marker files and compressed declaration data
    shutil.rmtree(build / "doc-data", ignore_errors=True)
    # HTML output directory
    shutil.rmtree(build / "doc", ignore_errors=True)
    # Manifest produced by doc-gen4's `fromDb`
    (build / "doc-manifest.json").unlink(missing_ok=True)


def lean_docs_placeholder(*, failed: bool) -> str:
    """Small fallback HTML for `lean/index.html` if docs aren't present."""
    title = "Lean API docs"
    status = "FAILED (stale fallback in use)" if failed else "UNAVAILABLE"
    body = (
        "<h1>Lean API docs</h1>\n"
        f"<p>Status: <strong>{status}</strong></p>\n"
        "<p>See <a href=\"../build-status.txt\">build-status.txt</a> for details.</p>\n"
        "<p><a href=\"../index.html\">Back to site</a></p>\n"
    )
    return (
        "<!doctype html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "  <meta charset=\"utf-8\" />\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
        f"  <title>{title}</title>\n"
        "</head>\n"
        "<body style=\"max-width:60rem;margin:2rem auto;padding:0 1rem;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;\">\n"
        f"{body}"
        "</body>\n"
        "</html>\n"
    )


def escape_html(s: str) -> str:
    """Escape a string for safe embedding in HTML."""
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#39;")
    )


def detect_main_lean_lib_name(root: Path) -> str:
    """Legacy helper: detect the main lean_lib name.

    Prefer `detect_project_root_module` for navbar/pruning.
    """
    # Minimal heuristic: parse root lakefile.toml for the first [[lean_lib]] name.
    lakefile = root / "lakefile.toml"
    if not lakefile.exists():
        return "GaudisCrypt"
    text = read_text(lakefile)
    # Very small TOML-ish parse.
    m = re.search(r"\[\[lean_lib\]\]\s*\n\s*name\s*=\s*\"([^\"]+)\"", text)
    if m:
        return m.group(1)
    return "GaudisCrypt"


def module_name_from_path(root: Path, lean_path: Path) -> str:
    """Convert `GaudisCrypt/Foo/Bar.lean` to module name `GaudisCrypt.Foo.Bar`."""
    """Convert /repo/GaudisCrypt/Foo/Bar.lean to GaudisCrypt.Foo.Bar."""
    rel = lean_path.relative_to(root)
    if rel.suffix != ".lean":
        raise ValueError(f"Not a .lean file: {lean_path}")
    parts = list(rel.with_suffix("").parts)
    return ".".join(parts)


def module_name_from_toplevel_file(root: Path, lean_path: Path) -> str:
    """Convert `./Foo.lean` to module name `Foo`."""
    """Convert /repo/Foo.lean to Foo."""
    rel = lean_path.relative_to(root)
    if rel.parent != Path(".") or rel.suffix != ".lean":
        raise ValueError(f"Not a top-level .lean file: {lean_path}")
    return rel.stem


def all_project_modules(root: Path, *, top: str = "GaudisCrypt") -> list[str]:
    """Return all project module names (root module + submodules)."""
    mods: list[str] = []
    # Include the root module file `GaudisCrypt.lean`.
    root_file = root / f"{top}.lean"
    if root_file.exists():
        mods.append(top)

    base = root / top
    if base.exists():
        for p in sorted(base.rglob("*.lean")):
            mods.append(module_name_from_path(root, p))

    # Exclude the autogenerated entrypoint if it exists.
    mods = [m for m in mods if m != f"{top}.DocEntrypoint"]
    return mods


def module_file_map(root: Path, *, top: str = "GaudisCrypt") -> dict[str, Path]:
    """Map module name -> .lean file path for project modules."""
    """Map module name -> source file path for project modules."""
    mp: dict[str, Path] = {}
    root_file = root / f"{top}.lean"
    if root_file.exists():
        mp[top] = root_file
    base = root / top
    if base.exists():
        for p in base.rglob("*.lean"):
            mp[module_name_from_path(root, p)] = p
    # Don't treat the autogenerated entrypoint as a normal source file.
    mp.pop(f"{top}.DocEntrypoint", None)
    return mp


_IMPORT_RE = re.compile(r"^\s*import\s+(.+?)\s*$")


def parse_imports_from_source(text: str) -> list[str]:
    """Parse module names from `import ...` lines.

    This is a deliberately simple parser: it handles `import A.B` and `import A B`.
    It ignores anything after `--` on the same line.
    """
    # This is a pragmatic parser used only to build an import graph for exclusions.
    out: list[str] = []
    for line in text.splitlines():
        m = _IMPORT_RE.match(line)
        if not m:
            continue
        rest = m.group(1)
        if "--" in rest:
            rest = rest.split("--", 1)[0]
        # Split on whitespace; drop empty.
        parts = [p for p in rest.strip().split() if p]
        for p in parts:
            # Strip simple punctuation that sometimes appears.
            p = p.strip("(){}[],")
            if not p:
                continue
            out.append(p)
    return out


def build_project_import_graph(root: Path, *, top: str = "GaudisCrypt") -> tuple[dict[str, set[str]], dict[str, set[str]]]:
    """Build a project-internal import graph.

    Returns:
    - imports: module -> set of modules it imports
    - dependents: module -> set of modules that import it
    """
    """Return (imports, dependents) restricted to project modules."""
    mp = module_file_map(root, top=top)
    project_mods = set(mp.keys())
    imports: dict[str, set[str]] = {m: set() for m in project_mods}
    dependents: dict[str, set[str]] = {m: set() for m in project_mods}

    for mod, path in mp.items():
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for imp in parse_imports_from_source(text):
            # Only track dependencies within this project.
            if imp in project_mods:
                imports[mod].add(imp)
                dependents[imp].add(mod)
    return imports, dependents


def dependent_closure(dependents: dict[str, set[str]], seeds: set[str]) -> set[str]:
    """Return `seeds` plus all modules that transitively depend on them."""
    """Return seeds plus all modules that transitively depend on them."""
    q = list(seeds)
    seen: set[str] = set()
    while q:
        cur = q.pop()
        if cur in seen:
            continue
        seen.add(cur)
        for d in dependents.get(cur, set()):
            if d not in seen:
                q.append(d)
    return seen


def write_doc_entrypoint(root: Path, *, excluded: set[str], top: str = "GaudisCrypt") -> Path:
    """Generate `./DocEntrypoint.lean` importing all non-excluded project modules.

    This file is created temporarily to drive doc-gen4.
    """
    """Write ./DocEntrypoint.lean importing all non-excluded project modules."""
    mods = all_project_modules(root, top=top)
    kept = [m for m in mods if m not in excluded]

    # IMPORTANT: `import` commands must come first (before any *commands* like `/-! ... -/`).
    # A regular block comment `/- ... -/` is fine before imports.
    lines: list[str] = [
        "/-",
        "AUTOGENERATED by scripts/build-gh-pages.py.",
        "",
        "This file is used ONLY for doc generation and should not be committed.",
        "It is created and removed by the build script.",
        "-/",
        "",
    ]
    for m in kept:
        lines.append(f"import {m}")
    lines.append("")
    # Optional module doc (after imports) so the generated module page has context.
    lines.extend(
        [
            "/-!",
            "Doc entrypoint (generated)",
            "",
            "This module is generated by `scripts/build-gh-pages.py` and imports a subset of the project.",
            "The goal is to keep doc generation working even if some files do not compile.",
            "",
            "Excluded modules are recorded in `excluded-modules.txt` on the `gh-pages` branch.",
            "-/",
            "",
        ]
    )
    path = root / "DocEntrypoint.lean"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def warn_if_overcommit_disabled() -> None:
    """Warn (but don't fail) if Linux memory overcommit isn't set to 'always'.

    The doc build spawns `doc-gen4` once per module -- thousands of times -- by
    `fork()`-ing the large (~8 GB) `lake` driver. Under the default heuristic
    overcommit (`vm.overcommit_memory=0`, or strict mode 2), those forks can be
    refused with ENOMEM ("cannot allocate memory") even when plenty of RAM is
    free, aborting the doc build partway. Mode 1 (always overcommit) avoids it;
    the duplicated pages are copy-on-write and backed by RAM+swap anyway.
    """
    try:
        mode = Path("/proc/sys/vm/overcommit_memory").read_text().strip()
    except OSError:
        return  # Not Linux (or no procfs): nothing to check.
    if mode == "1":
        return
    print(
        f"WARNING: vm.overcommit_memory={mode!r} (not '1'). The doc build fork()s a\n"
        "large `lake` process thousands of times to run doc-gen4; under this setting\n"
        "those forks may fail with ENOMEM ('cannot allocate memory') even with free\n"
        "RAM, aborting the build. Recommended:\n"
        "  sudo sysctl -w vm.overcommit_memory=1\n"
        "(persist via /etc/sysctl.d/99-overcommit.conf). Continuing anyway...",
        file=sys.stderr,
    )


def build_docs(root: Path, *, target: str, do_update: bool = True) -> tuple[bool, str, Path | None]:
    """Build a Lake target and return (ok, combined_log, doc_dir)."""
    """Return (success, log_output, doc_dir)."""
    if not (root / "lakefile.toml").exists():
        raise SystemExit("Missing lakefile.toml in repo root")

    logs: list[str] = []

    # Ensure deps are fetched.
    if do_update:
        logs.append(run(["lake", "update"], cwd=root).stdout)

    # Pull precompiled oleans if available (mathlib cache). Non-fatal if it fails.
    if do_update:
        cp_cache = run(["lake", "exe", "cache", "get"], cwd=root, check=False)
        logs.append(cp_cache.stdout)

    # Single-threaded build to avoid OOM (see notes in CLAUDE.md / commit history).
    # `LEAN_NUM_THREADS=1` sizes Lake's job scheduler (built on the Lean task runtime)
    # down to a single worker, so at most one memory-hungry `doc-gen4` process runs at
    # a time. This Lake version has no `-j`/`--jobs` flag; the env var is the lever.
    cp = run(["lake", "build", target], cwd=root, check=False, env={"LEAN_NUM_THREADS": "1"})
    logs.append(cp.stdout)

    # doc-gen4 writes to `.lake/build/doc`.
    # (Some setups additionally symlink/copy elsewhere; we stick to the default.)
    doc_dir = root / ".lake" / "build" / "doc"
    ok = (cp.returncode == 0) and doc_dir.exists() and (doc_dir / "index.html").exists()
    return ok, "\n".join(logs).strip(), (doc_dir if doc_dir.exists() else None)


def parse_failing_modules(build_log: str) -> list[str]:
    """Extract failing module names from Lake output."""
    """Extract failing module-ish names from Lake output."""
    mods: list[str] = []
    # Most reliable: the summary block.
    for m in re.finditer(r"^\-\s+(GaudisCrypt(?:\.[A-Za-z0-9_']+)+)\s*$", build_log, flags=re.MULTILINE):
        mods.append(m.group(1))
    # Also look at the explicit "Building ..." line.
    for m in re.finditer(r"\bBuilding\s+(GaudisCrypt(?:\.[A-Za-z0-9_']+)+)\b", build_log):
        mods.append(m.group(1))
    # Preserve order, de-dup.
    seen: set[str] = set()
    out: list[str] = []
    for m in mods:
        if m not in seen:
            seen.add(m)
            out.append(m)
    return out


def build_docs_with_auto_exclude(root: Path) -> tuple[bool, str, Path | None, set[str]]:
    """Build docs by iteratively excluding failing modules.

    This repeatedly:
    - deletes doc-gen4 outputs (so closure cannot go stale)
    - writes `DocEntrypoint.lean`
    - runs `lake build DocEntrypoint:docs`
    - parses failing modules and excludes them (plus dependents)
    """
    """Attempt doc build, iteratively excluding failing modules from a generated entrypoint."""
    excluded: set[str] = set()

    # Build docs for the transitive import closure of the generated entrypoint module.
    # With the Lake TOML DSL, module facets are addressed as `Module.Name:facet`.
    docs_target = "DocEntrypoint:docs"

    all_mods = set(all_project_modules(root))
    _, dependents = build_project_import_graph(root)
    # Hard cap to avoid infinite loops if parsing fails.
    max_iters = max(5, min(200, len(all_mods) + 5))

    combined_logs: list[str] = []

    # Do the expensive dependency update/cache fetch once.
    for i in range(max_iters):
        reset_docgen_outputs(root)
        write_doc_entrypoint(root, excluded=excluded)
        ok, log, doc_dir = build_docs(root, target=docs_target, do_update=False)
        combined_logs.append(f"\n===== doc build attempt {i+1} (excluded={len(excluded)}) =====\n")
        combined_logs.append(log)
        if ok:
            if VERBOSE:
                print(f"doc build succeeded after {i+1} attempt(s)")
                if excluded:
                    print(f"excluded modules ({len(excluded)}):")
                    for m in sorted(excluded):
                        print(f"  {m}")
            return True, "\n".join(combined_logs).strip(), doc_dir, excluded

        failing_candidates = parse_failing_modules(log)
        failing_set = {m for m in failing_candidates if m in all_mods and m not in excluded}
        if not failing_set:
            # Can't identify what to exclude. Give up and fall back to stale publish.
            return False, "\n".join(combined_logs).strip(), doc_dir, excluded

        # Exclude the failing modules and everything that depends on them.
        newly_excluded = dependent_closure(dependents, failing_set)
        if VERBOSE:
            print(f"doc build failed; excluding {len(newly_excluded)} module(s) due to failures:")
            for m in sorted(failing_set):
                print(f"  failing: {m}")
            # Show only the newly added exclusions (not the whole set), to keep output readable.
            for m in sorted(newly_excluded):
                if m not in excluded:
                    print(f"  exclude: {m}")
        excluded |= newly_excluded

    return False, "\n".join(combined_logs).strip(), None, excluded


def write_build_metadata(worktree_root: Path, *, success: bool, head_sha: str, build_time_utc: str, log_excerpt: str) -> None:
    """Write build status files into the gh-pages worktree."""
    meta = {
        "success": success,
        "head": head_sha,
        "build_time_utc": build_time_utc,
    }
    write_text(worktree_root / "build-status.json", json.dumps(meta, indent=2) + "\n")
    # Keep a small human-readable status too.
    status = "SUCCESS" if success else "FAILED (stale content used)"
    txt = f"Build status: {status}\nCommit: {head_sha}\nTime (UTC): {build_time_utc}\n"
    if (log_excerpt or "").strip():
        txt += "\n--- build output excerpt ---\n" + (log_excerpt.strip() + "\n")
    write_text(worktree_root / "build-status.txt", txt)


def extract_error_excerpt(build_log: str) -> str:
    """Extract a small tail excerpt from the build log for reporting."""
    # Take the tail-ish part of the log (most useful), but keep it small.
    lines = build_log.splitlines()
    if not lines:
        return ""
    tail = lines[-80:]
    return "\n".join(tail)


def main() -> int:
    """CLI entry point."""
    ap = argparse.ArgumentParser()
    ap.add_argument("--branch", default="gh-pages", help="Destination branch (default: gh-pages)")
    ap.add_argument("--push", action="store_true", help="Push gh-pages to origin after committing")
    ap.add_argument(
        "--keep-cname",
        action="store_true",
        help=(
            "Preserve an existing CNAME file on gh-pages during successful rebuilds. "
            "Use this if you configured a custom domain for GitHub Pages."
        ),
    )
    ap.add_argument(
        "--verbose",
        action="store_true",
        help="Print executed commands and exclusion/commit info",
    )
    ap.add_argument(
        "--no-api",
        action="store_true",
        help=(
                "Do not rebuild Lean API docs. Only update the website from docs/website/ and reuse the existing "
            "gh-pages/lean/ directory as-is."
        ),
    )
    # Optional shell completion (requires `python3-argcomplete` / `argcomplete` installed).
    try:
        import argcomplete  # type: ignore

        argcomplete.autocomplete(ap)
    except Exception:
        pass

    args = ap.parse_args()

    global VERBOSE
    VERBOSE = bool(args.verbose)

    root = repo_root()
    head_sha = current_head_sha(root)
    build_time_utc = _dt.datetime.now(_dt.UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    # The script generates its own doc entrypoint and does not rely on the main
    # library being buildable.

    # In --no-api mode, we skip doc generation entirely.
    if args.no_api:
        # Use system temp dir for worktrees; avoid hardcoding shared paths.
        wt = Path(tempfile.gettempdir()) / f"gaudis-crypt-gh-pages-{os.getpid()}"
        ensure_worktree(root, args.branch, wt)
        try:
            preserve = set()
            if args.keep_cname and (wt / "CNAME").exists():
                preserve.add("CNAME")

            # Snapshot previous API docs so we can restore them after rebuilding
            # the manual website.
            old_lean: Path | None = None
            if not (wt / "lean").exists():
                raise SystemExit(
                    "--no-api requested but `lean/` is missing on gh-pages. "
                    "Run the script once without --no-api to publish API docs first."
                )

            old_lean = Path(tempfile.gettempdir()) / f"gaudis-crypt-gh-pages-lean-{os.getpid()}"
            if old_lean.exists():
                shutil.rmtree(old_lean)
            shutil.copytree(wt / "lean", old_lean)

            remove_all_except_git(wt, preserve=preserve)

            site_src = root / "docs" / "website"
            if not site_src.exists():
                raise SystemExit("Missing `docs/website/` directory on main branch.")

            # Build website into a clean gh-pages worktree...
            run_jekyll_build(site_src, wt)

            # ...then restore previously published API docs.
            if old_lean is not None:
                if (wt / "lean").exists():
                    shutil.rmtree(wt / "lean")
                shutil.move(str(old_lean), str(wt / "lean"))

            # Ensure Jekyll runs: remove stale `.nojekyll` if present.
            (wt / ".nojekyll").unlink(missing_ok=True)

            # Basic build status (no doc build attempted).
            write_text(
                wt / "build-status.json",
                json.dumps({"success": True, "head": head_sha, "build_time_utc": build_time_utc, "no_api": True}, indent=2)
                + "\n",
            )
            write_text(
                wt / "build-status.txt",
                f"Build status: SUCCESS\nCommit: {head_sha}\nTime (UTC): {build_time_utc}\nMode: no-api\n",
            )

            run(["git", "add", "-A"], cwd=wt)
            cp_status = run(["git", "status", "--porcelain"], cwd=wt)
            if cp_status.stdout.strip():
                msg = f"Update site (no-api) for {head_sha[:12]}"
                if VERBOSE:
                    print(f"git commit -m {msg!r} (on {args.branch})")
                run(["git", "commit", "-m", msg], cwd=wt)
            else:
                print("No changes to commit on gh-pages.")

            if args.push:
                if VERBOSE:
                    print(f"git push origin {args.branch}")
                run(["git", "push", "origin", args.branch], cwd=wt)

            print("Updated site; reused existing API docs (--no-api).")
            return 0
        finally:
            # Clean up any temp lean snapshot.
            try:
                if 'old_lean' in locals() and old_lean is not None and old_lean.exists():
                    shutil.rmtree(old_lean, ignore_errors=True)
            except Exception:
                pass
            run(["git", "worktree", "remove", "--force", str(wt)], cwd=root, check=False)

    # The doc build is fork-heavy; warn (non-fatally) if overcommit isn't enabled.
    warn_if_overcommit_disabled()

    # Generated entrypoint is created in the repo root; remove it afterwards.
    entrypoint_path = root / "DocEntrypoint.lean"
    try:
        ok, log, doc_dir, excluded = build_docs_with_auto_exclude(root)
        error_excerpt = extract_error_excerpt(log)

        # "ok" means doc-gen4 produced a coherent doc site for the entrypoint.
        # If exclusions are non-empty, this is a partial build and we keep older
        # docs for excluded modules as stale fallback.
        full_rebuild = ok and not excluded

        if not ok:
            # User requested: if docs do not build at all, do not touch gh-pages.
            # Still write logs to disk so the user can inspect what went wrong.
            out_dir = root / ".lake" / "build"
            full_log_path = out_dir / "doc-build.log"
            excerpt_path = out_dir / "doc-build-excerpt.log"
            write_text(full_log_path, (log or "").strip() + "\n")
            write_text(excerpt_path, (error_excerpt or "").strip() + "\n")
            print(f"doc build failed; wrote log to {full_log_path} and excerpt to {excerpt_path}")
            raise SystemExit("doc build failed; gh-pages not updated")

        # Use system temp dir for worktrees; avoid hardcoding shared paths.
        wt = Path(tempfile.gettempdir()) / f"gaudis-crypt-gh-pages-{os.getpid()}"
        ensure_worktree(root, args.branch, wt)

        # Prepare gh-pages content.
        preserve = set()
        if args.keep_cname and (wt / "CNAME").exists():
            preserve.add("CNAME")

        # Save old HTML for excluded modules before modifying the worktree.
        old_excluded_html: dict[str, str] = {}
        if excluded:
            for mod in excluded:
                rel = module_to_html_relpath(mod)
                p = wt / "lean" / rel
                if p.exists():
                    old_excluded_html[mod] = read_text(p)

        # Rebuild gh-pages content from scratch (manual site + freshly generated docs).
        remove_all_except_git(wt, preserve=preserve)

        # We intentionally keep `.nojekyll` absent.
        # The manual site is built locally (Jekyll), so GitHub Pages/Jekyll isn't required.

        # Always: build manual site content locally.
        site_src = root / "docs" / "website"
        if not site_src.exists():
            raise SystemExit("Missing `docs/website/` directory on main branch. Create it with your manual pages.")
        run_jekyll_build(site_src, wt)

        # We build the site locally with Jekyll; make sure a stale `.nojekyll`
        # doesn't get committed accidentally.
        (wt / ".nojekyll").unlink(missing_ok=True)

        # Copy docs output.
        # We put doc-gen4 output under `lean/` to keep manual pages at root.
        docs_dst = wt / "lean"
        if docs_dst.exists():
            shutil.rmtree(docs_dst)
        if doc_dir and doc_dir.exists():
            # Copy full doc-gen4 output, then postprocess to keep only project pages.
            copy_tree(doc_dir, docs_dst)
            project_root = detect_project_root_module(root)
            postprocess_doc_tree(docs_dst, project_root)

        # Ensure we always have an entrypoint for the docs link on the manual site.
        if not (docs_dst / "index.html").exists():
            write_text(docs_dst / "index.html", lean_docs_placeholder(failed=not ok))

        # Remove the autogenerated entrypoint module page from the published docs.
        # (We keep the rest of the docs that were generated via the entrypoint.)
        if ok:
            for rel in [Path("DocEntrypoint.html"), Path("DocEntrypoint") / "Index.html"]:
                p = docs_dst / rel
                if p.exists():
                    p.unlink()

        # Stale-per-theory disclaimer:
        # For excluded modules we keep older HTML pages from gh-pages. For those pages
        # (i.e., not regenerated in this run), inject a banner saying the theory is stale.
        # For excluded modules, restore old HTML pages (if any) and inject a banner.
        # This ensures we don't keep stale pages for removed modules.
        stale_banner = stale_theory_banner_block(head_sha=head_sha, build_time_utc=build_time_utc)
        if excluded:
            for mod in excluded:
                old_html = old_excluded_html.get(mod)
                if not old_html:
                    continue
                rel = module_to_html_relpath(mod)
                out_path = docs_dst / rel
                html2 = inject_stale_banner(strip_stale_banner(old_html), stale_banner)
                write_text(out_path, html2)

        # After pruning non-project docs, internal links to dependency modules would be broken.
        # Rewrite those links to mathlib4_docs.
        rewrite_broken_links_to_online_docs(docs_dst)

        # Rewrite navbar.html to include only project theories, including excluded ones.
        project_root = detect_project_root_module(root)
        generated_relpaths: set[Path] = set()
        if doc_dir is not None:
            generated_relpaths = load_doc_manifest(doc_dir)
        navbar_modules = build_navbar_module_list(project_root, generated_relpaths=generated_relpaths, excluded=set(excluded))
        write_text(docs_dst / "navbar.html", generate_project_navbar(docs_dst, project_root, navbar_modules))

        # On full rebuild, make sure there are no stale banners lingering anywhere.
        if full_rebuild:
            for p in iter_html_files(docs_dst):
                html = read_text(p)
                html2 = strip_stale_banner(html)
                if html2 != html:
                    write_text(p, html2)

        write_build_metadata(wt, success=ok, head_sha=head_sha, build_time_utc=build_time_utc, log_excerpt=error_excerpt)

        # Record whether this was a partial doc build.
        if excluded:
            write_text(wt / "doc-partial.txt", "partial doc build: excluded modules present\n")

        # Also record excluded modules (useful for debugging failures / missing docs).
        if excluded:
            write_text(wt / "excluded-modules.txt", "\n".join(sorted(excluded)) + "\n")

        # Commit.
        run(["git", "add", "-A"], cwd=wt)
        cp_status = run(["git", "status", "--porcelain"], cwd=wt)
        if cp_status.stdout.strip():
            msg = f"Update site/docs for {head_sha[:12]}"
            if not ok:
                msg = f"Update site/docs (stale) for {head_sha[:12]}"
            if VERBOSE:
                print(f"git commit -m {msg!r} (on {args.branch})")
            run(["git", "commit", "-m", msg], cwd=wt)
        else:
            print("No changes to commit on gh-pages.")

        if args.push:
            if VERBOSE:
                print(f"git push origin {args.branch}")
            run(["git", "push", "origin", args.branch], cwd=wt)

        if full_rebuild:
            print("Docs build succeeded; gh-pages fully regenerated.")
        else:
            print("Docs build succeeded with exclusions; restored older HTML for excluded modules.")
        return 0
    finally:
        # Clean up entrypoint source file.
        entrypoint_path.unlink(missing_ok=True)
        # Detach worktree (if it was created).
        wt = locals().get("wt")
        if wt is not None:
            run(["git", "worktree", "remove", "--force", str(wt)], cwd=root, check=False)


if __name__ == "__main__":
    raise SystemExit(main())
